
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'claim_to_fame'
version: '1.0.0'
config-version: 2

profile: 'dbt-learn'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

seeds:
  claim_to_fame:
    ehr_data:
      +schema: ehr_data
    billing_data:
      +schema: billing_data
